info:
  namespace: vspe_dimensions

font_images:
  distant_world:
    path: dimension_types/distant_world.png
    scale_ratio: 9
    y_position: 8

  close_world:
    path: dimension_types/close_world.png
    scale_ratio: 9
    y_position: 8

  hollow_world:
    path: dimension_types/void_world.png
    scale_ratio: 9
    y_position: 8

  normal_world:
    path: dimension_types/normal_world.png
    scale_ratio: 9
    y_position: 8

  aquatic_world:
    path: dimension_types/aquatic_world.png
    scale_ratio: 9
    y_position: 8

  frozen_world:
    path: dimension_types/frozen_world.png
    scale_ratio: 9
    y_position: 8

  nether_world:
    path: dimension_types/nether_world.png
    scale_ratio: 9
    y_position: 8

  dark_world:
    path: dimension_types/dark_world.png
    scale_ratio: 9
    y_position: 8

  bright_world:
    path: dimension_types/bright_world.png
    scale_ratio: 9
    y_position: 8

  barren_world:
    path: dimension_types/barren_world.png
    scale_ratio: 9
    y_position: 8

  arboreal_world:
    path: dimension_types/arboreal_world.png
    scale_ratio: 9
    y_position: 8

  elemental_world:
    path: dimension_types/elemental_world.png
    scale_ratio: 9
    y_position: 8

  dream_world:
    path: dimension_types/dream_world.png
    scale_ratio: 9
    y_position: 8

  abstract_world:
    path: dimension_types/abstract_world.png
    scale_ratio: 9
    y_position: 8

  alien_world:
    path: dimension_types/alien_world.png
    scale_ratio: 9
    y_position: 8

  futuristic_world:
    path: dimension_types/futuristic_world.png
    scale_ratio: 9
    y_position: 8

  ancient_world:
    path: dimension_types/ancient_world.png
    scale_ratio: 9
    y_position: 8

  aether_world:
    path: dimension_types/aether_world.png
    scale_ratio: 9
    y_position: 8
