/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "vickyes-survival-plus-essentials"
// include(":structure")
include(":structure_loader")
include(":VSPE")
include(":V-NMS")

pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

include("V-NMS:1_20_R4")
findProject(":V-NMS:1_20_R4")?.name = "1_20_R4"
include("VSPE:1_20_4")
findProject(":VSPE:1_20_4")?.name = "1_20_4"
