/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "vickyes-survival-plus-essentials"
// include(":structure")
include(":structure_loader")
include(":VSPE")
include(":V-NMS")

pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}