/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "vickyes-survival-plus-essentials"
// include(":structure")
include(":structure_loader")
include(":VSPE")

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://maven.minecraftforge.net/") {
            name = "MinecraftForge"
        }
    }
}

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}

include(":VSPE:1_20_4")
findProject(":VSPE:1_20_4")?.name = "1_20_4"
