/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    maven("https://jitpack.io")
    maven("https://repo.maven.apache.org/maven2/")
    maven("https://repo.onarandombox.com/content/groups/public/")
    maven("https://repo.codemc.io/repository/maven-public/")
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://oss.sonatype.org/content/groups/public/")
    maven("https://repo.extendedclip.com/content/repositories/placeholderapi/")
    maven("https://mvn.lumine.io/repository/maven-public/")
    maven("https://www.matteodev.it/spigot/public/maven/")
    maven("https://repo.dmulloy2.net/repository/public/")
    maven("https://repo.codemc.io/repository/maven-snapshots/")
    maven("https://maven.enginehub.org/repo/")
    maven("https://maven.pkg.github.com/VickyE2/VickyE-s_Utilities"){
        credentials {
            val usernameValue = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                ?: throw GradleException("Publishing username not set in 'gpr.user' property or 'USERNAME' environment variable")
            username = usernameValue.toString()
            val passwordValue = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            ?: throw GradleException("Publishing password not set in 'gpr.key' property or 'TOKEN' environment variable")
            password = passwordValue.toString()
        }
    }
}

dependencies {
    implementation("org.reflections:reflections:0.10.2")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0")
    testImplementation("org.junit.jupiter:junit-jupiter-params:5.11.0")
    implementation("org.yaml:snakeyaml:2.4")
    implementation("org.jetbrains:annotations:24.1.0")
    compileOnly("io.github.vickye2:vicky-utils-core:0.0.1")
    compileOnly("com.dfsek.terra:api:6.5.0-BETA+060cbfd0c")
    compileOnly("com.dfsek.terra:manifest-addon-loader:1.0.0-BETA+fd6decc70")
}

group = "org.vicky.vspe.addon"
version = "1.0.0-ALPHA"
description = "structure_loader"

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
